### ISSUE TITLE
Date sorting issue

### ISSUE THREAD

**Issue by MikePulsiferDOL** [USDepartmentofLabor/Quarry#22]
There appears to be an issue with date sorting.  For example, when using START-DATE = 1990 and DESC, a user gets dates from 2013-2012.  If they use ASC, they start in 1990.

**Comment by johnsonpatrickk** [comment]
Thanks for the feedback Mike. Can you copy and paste an example of the dataset you tried to access with the start and end date format?

**Comment by neilneyman** [comment]
That sounds like it's doing exactly as documented?  The Start-Date=1990 would return records from 1990 and later.  But Sorting as desc would then return the latest records first.

**Comment by Supreet7** [comment]
This issue is resolved  in  version 2.0.3
