### ISSUE TITLE
Parse and store ILAB Child Labor data

### ISSUE THREAD

**Issue by joey-spooner** [USDepartmentofLabor/Quarry#27]

**Comment by johnsonpatrickk** [comment]
@spoonstein ILAB Data is ready for review in QA. Please add add Nischal and Maneka to this repository/issue for review.

**Comment by johnsonpatrickk** [comment]
he Quarry Staging datasets for ILAB-Child Labor have been verified and the datasets can be accessed successfully. The screenshots of the validation are attached. Test Passed.

**Comment by johnsonpatrickk** [comment]
Request to add ILAB-Child Labor datasets into production is in progress...

**Comment by johnsonpatrickk** [comment]
All ILAB-ChildLabor datasets have been released to production.
